### PR TITLE
Update MPlayer.cs UI position

### PR DESCRIPTION
**Pull request by whismerhill**
adapted UI position for 1680x1050 16/10 screen resolutions. Untested on other resolutions, sorry don't have the hardware to test for 16/9.

### CODE REVIEW

**Comment by whismerhill** [comment]
tested on 1600x900. was working locally

**Comment by whismerhill** [comment]
now also tested out by friend in 1920x1080 working fine

**Comment by abluescarab** [comment]
I merged this to test it, but it's too far to the right. Is this what you intended?

**Comment by whismerhill** [comment]
@abluescarab 
O_o
not at all
this is how it looks on my side with the changes I proposed : http://steamcommunity.com/sharedfiles/filedetails/?id=790732291

I thought maybe it was a mod interaction but apparently not, I disabled all mods to test it afterward.

I am on tmodloader 0.8.3.5 & terraria 1.3.3.3, are you too ?

**Comment by abluescarab** [comment]
@whismerhill How does it look these days?

**Comment by whismerhill** [comment]
@abluescarab it took a long time for me to go back to terraria & modding, I was kinda not using it for all this time.
and these days it works fine out of the box

**Pull request merged**
